### ISSUE TITLE
Include address formatting on EE Country Settings page

### ISSUE THREAD

**Issue by greyowl7** [joshfeck/remove-extra-editor-buttons#1]
Countries format their addresses differently. Especially the fields City, Zip, State, Country may need to be displayed in a different sequence or omitted entirely. Just as the date and time format is set in the WordPress settings (but not applied in EE!) and the currency details are set in EE, so the address element sequence could be customisable.

**Comment by joshfeck** [comment]
@greyowl7 I'm sorry for the confusion, but this repository has nothing to do with an EE Country Settings page. You probably meant to post this somewhere else.

**Comment by greyowl7** [comment]
Hi Josh

Did I misunderstand your answer to my remark on
https://eventespresso.com/topic/reformat-address-details/:
>
> The dev team is working on other tasks at the moment. They do welcome pull
> requests if you’d like to add those options.
>
> https://github.com/eventespresso/event-espresso-core/
>

Friedliche Grüsse / Hearty greetings
Viktor Steiner

**Comment by joshfeck** [comment]
You must not have understood. A pull request isn't the same thing as leaving a comment, and my answer included a link to the Event Espresso github repository. This is is a repository for a different plugin.
